node.name = "emqx@127.0.0.1"

dashboard.listeners.http.bind = 0

mqtt {
  peer_cert_as_username = cn
}

listeners.ssl.default {
  bind = "0.0.0.0:8883"
  max_connections = 1024
  ssl_options {
    cacertfile = "/opt/emqx/etc/certs/ca.crt"
    certfile = "/opt/emqx/etc/certs/broker.crt"
    keyfile = "/opt/emqx/etc/certs/broker.key"
    verify = verify_peer
    fail_if_no_peer_cert = true
    versions = ["tlsv1.3", "tlsv1.2"]
  }
}

listeners.tcp.default.enable = false
listeners.ws.default.enable = false
listeners.wss.default.enable = false

authorization {
  no_match = deny
  deny_action = ignore
  sources = [
    {
      type = file
      enable = true
      path = "/opt/emqx/etc/acl.conf"
    }
  ]
}
